config/routes.rb
Rails.application.routes.draw do
  mount Thredded::Engine => '/forum'


  devise_for :organizations, path: 'organizations', controllers: { sessions: 'organizations/sessions', registrations: 'organizations/registrations' }
  devise_for :users, path: 'users', controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :contacts, only: [:new, :create]
  get 'landing', to: "organizations#landing"
  get 'contact_us', to: "pages#contact_us"

  resources :organizations, only: [:show, :edit, :destroy, :update]

  # resources :users, only: [:new, :create, :show, :edit, :update]
  resources :projects do
    resources :teams, only: [:new, :index, :create]
    get 'classroom', to: :classroom, controller: 'projects'
    resources :proposals, only: [:edit, :show, :create, :destroy, :update]
    get 'proposal/:id/confirm', to: 'proposals#confirm', as: 'proposal_confirm'
  end
  resources :proposals, only: [:index, :destroy, :update]
  resources :teams, only: [:show, :delete, :edit, :update] do
    resources :team_members, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]

  #for payments
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="text-center">
    <%= image_tag "logo_thing.png", class: "slice-footer", alt: "Rookstars" %>
  </div>
  <div class="text-center">
   <p style="color: white;">coding to <span id="title-typed"></span></p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
  <div class="navbar-container">
    <% unless current_page? root_path %>
    <div class="navbar-top">
      <div class="back">
        <a href="javascript:history.back()", class="back-text ">
          <i class="back-btn fas fa-arrow-left"></i>
        </a>
      </div>
      <div class="brand">
        <%= link_to root_path do  %>
        <%= image_tag "logo.png", class: "navbar-wagon-brand" %>
        <% end %>
      </div>

      <div class="please-work">
        <% if user_signed_in? %>
        <div class="navbar-top-item">
          <div class="dropdown">
            <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-top-menu" , data:{toggle: "dropdown"} %>
            <ul class="dropdown-menu dropdown-menu-right navbar-top-dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user)  %></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %></li>
              </ul>
            </div>
          </div>
        </div>
        <% elsif  organization_signed_in? %>
        <div class="navbar-top-item">
          <div class="dropdown">
            <%= image_tag current_organization.avatar, class: "avatar dropdown-toggle", id: "navbar-top-menu" , data:{toggle: "dropdown"} %>
            <ul class="dropdown-menu dropdown-menu-right navbar-top-dropdown-menu">
              <li><%= link_to "Profile", organization_path(current_organization)  %></li>
              <li><%= link_to destroy_organization_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %></li>
              </ul>
            </div>
          </div>
        </div>
        <% else %>
        <div class="nav-content">
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-top-eric custom-primary-btn" %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>