config/routes.rb
Rails.application.routes.draw do
  mount Thredded::Engine => '/forum'


  devise_for :organizations, path: 'organizations', controllers: { sessions: 'organizations/sessions', registrations: 'organizations/registrations' }
  devise_for :users, path: 'users', controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :contacts, only: [:new, :create]
  get 'landing', to: "organizations#landing"
  get 'contact_us', to: "pages#contact_us"

  resources :organizations, only: [:show, :edit, :destroy, :update]

  # resources :users, only: [:new, :create, :show, :edit, :update]
  resources :projects do
    resources :teams, only: [:new, :index, :create]
    get 'classroom', to: :classroom, controller: 'projects'
    resources :proposals, only: [:edit, :show, :create, :destroy, :update]
    get 'proposal/:id/confirm', to: 'proposals#confirm', as: 'proposal_confirm'
  end
  resources :proposals, only: [:index, :destroy, :update]
  resources :teams, only: [:show, :delete, :edit, :update] do
    resources :team_members, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]

  #for payments
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organization
  has_many :proposals
  has_many :teams, through: :proposals
  has_one :thredded_messageboard_group
  validates :title, :description, :due_date, :status, :budget, presence: true
  mount_uploader :photo, PhotoUploader, :mount_on => :photo
  monetize :price_cents
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @projects = policy_scope(Project)
  end

  def show
    set_params
    authorize @project
    @organization = Organization.find(@project.organization_id)
    @project_member = is_part_of_project?
  end

  def new
    @project = Project.new
    @proposal = Proposal.new
    authorize @project
  end

  def create
    if current_user.class == Organization.class
      @project = Project.new(valid_params)
      authorize @project
      @project.organization = current_user
      if @project.save
        redirect_to project_path(@project)
      else
        render :new
      end
    else
      @project = Project.new(user_project_params)
      @project.status = "Done"
      @project.due_date = DateTime.now.to_date
      @project.budget = 100
      if @organization = Organization.find_by(name: params[:project][:organization])
        @project.organization = @organization
      else
        @organization = Organization.create(name: params[:project][:organization], description: "selfcreated", email:"selfcreated#{Organization.last.id}@rook.com", password:"19823747288")
      end
      authorize @project
      @team = Team.new(about_us: current_user.about_me)
      team_member = TeamMember.create(team: @team, user: current_user, lead_dev: true)
      if @project.save
        proposal = Proposal.create(team: @team, project: @project, status: "Confirmed")
        redirect_to user_path(current_user)
      else
        render :new
      end
    end
  end

  def update
    set_params
    @proposal = Proposal.find(params[:id])
    redirect_to project_proposal_path(@project, @proposal)
    authorize @project
  end

  def classroom
    @project = Project.find(params[:project_id])
    authorize @project
  end

  private

  def is_part_of_project?
    @project.proposals.each do |proposal|
      if proposal.status == "Confirmed"
        @joinable = proposal.joinable
        proposal.team_members.each do |team_member|
          return true if team_member.user == current_user
        end
      else
        proposal.team_members.each do |team_member|
          @proposal_pending = team_member.user == current_user
          @proposal = proposal if team_member.user == current_user
        end
      end
    end
    return false
  end

  def set_params
    @project = Project.find(params[:id])
  end

  def valid_params
    params.require(:project).permit(:title, :description, :due_date, :status, :budget, :photo)
  end

  def user_project_params
    params.require(:project).permit(:title, :description, :photo, :db_sql, :maps, :forms, :mail_integration, :messaging_integration, :sign_up_log_in, :payment_integration)
  end
end

app/views/projects/classroom.html.erb
<div class="header-container-small" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.18) 50%), url('<%= cl_image_path @project.photo, crop: :fill %>'); background-attachment: fixed">
  <div class="header-content">
    <div class="intro-text">
      <p class="text-center">Your Project Classroom For:</p>
      <h1> <%= @project.title %> for <%= @project.organization.name %></p></h1>
    </div>
  </div>
</div>
<br>
<div class="classroom-container">
  <div class="container">
    <div class="container-fluid">
      <div class="col-xs-12">
        <div id="myKanban">
        </div>
      </div>
    </div>
  </div>
  <%= javascript_pack_tag 'jkanban' %>
</div>
</div>
<%= form_tag thredded_path, method: :get do %>
<button class="msg-button" type="submit"><i class="fas fa-comments"></i></button>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<div class="header-container-small" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.18) 50%), url('<%= cl_image_path "people-coffee-tea-meeting" %>'); background-size: cover; background-position: initial; background-attachment: fixed;">
  <div class="header-content">
    <div class="text-center intro-text">
      <h1>Find your favorite cause</h1>
    </div>
  </div>
</div>
<br>
<div class="container-cards">
  <!-- <h1 style="color: #005484;" class="text-center">Hop on a project</h1> -->
  <br>
<div class="container">
<%= render 'components/cards' %>
</div>
</div>

app/views/projects/new.html.erb
  <%= render "components/new_project_form", project: @project %>

app/views/projects/show.html.erb
<% content_for :meta_title, "#{@project.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @project.description %>
<% content_for :meta_image, cl_image_path(@project.photo) %>


<div class="header-container-small" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.18) 50%), url('<%= cl_image_path @project.photo %>'); background-size: cover; background-position: center; background-attachment: fixed">
  <div class="header-content">
    <div class="text-center intro-text">
      <h1 class="text-center">Project For <%= @organization.name %></h1>
      <br>
      <% if @project.status == "Done" || @joinable %>
            <p>This project can not be joined</p>
          <% else %>
          <div class="cta-button">
            <%= link_to "Join This Project", new_project_team_path(@project), class: "custom-primary-btn" %>
          </div>
          <% end %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="two-column-content">
    <div class="row">
      <div class="double-cta">
        <div class="left-cta col-xs-12 col-md-6" style="background-image: url('<%= cl_image_path 'bg2.jpg' %>'); background-size: cover; background-position: center">
          <div class="cta-content">
            <hr>
            <div class="text">
              <h1><%= @organization.name %></h1>
             <strong> <p class="tag-label">About the NGO:</p></strong>
              <p><%= @organization.description %></p>

            </div>
          </div>
        </div>
      </div>
      <div class="right-cta col-xs-12 col-md-6" style="background-image: url('<%= cl_image_path 'bg3.jpg' %>'); background-size: cover; background-position: center">
        <div class="cta-content">
          <hr>
          <div class="text text-overflow">
            <h1>About the Project</h1>
            <strong><p class="tag-label">Project:</p></strong>
            <p><%= @project.title %></p><br>
            <strong><p class="tag-label">Project details:</p></strong>
            <p> <%= @project.description %></p><br>
            <strong><p class="tag-label">Due date:</p></strong>
            <p><%= @project.due_date.strftime("%m - %d - %Y")%></p><br>
           <strong><p class="tag-label">Budget:</p> <p>€<%= @project.budget %> </p>
          <% if @project.status == "Done" || @joinable %>
            <p>This project can not be joined</p>
          <% elsif @proposal_pending %>
            <p>You have a pending application for this project.</p>
            <br>
            <%= link_to "View Project Status", project_proposal_confirm_path(@project, @proposal.id), class: "custom-primary-btn" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<% if current_user.class == Organization.class %>
<div class="one-column-cta" style="background-image: url('<%= cl_image_path 'bg.jpg' %>'); background-size: cover; background-position: center">
  <div class="container-fluid">
    <div class="cta-content">
      <hr>
      <div class="text text-center">
        <h1>Are You an Organization</h1>
        <p>Improve your digital presence with help of young profesionals.</p>
      </div>
      <div class="cta-button">
        <%= link_to "start", new_project_path, class: "custom-primary-btn" %>
      </div>
    </div>
  </div>
</div>
<% elsif @project_member %>
<div class="one-column-cta" style="background-image: url('<%= cl_image_path 'bg.jpg' %>'); background-size: cover; background-position: center">
  <div class="container-fluid">
    <div class="cta-content">
      <hr>
      <div class="text text-center">
        <h1>This is one of your projects</h1>
        <p>See your office</p>
      </div>
      <div class="cta-button">
        <%= link_to "Office", project_classroom_path(params[:id]), class: "custom-primary-btn" %>
      </div>
    </div>
  </div>
</div>
<% end %>