config/routes.rb
Rails.application.routes.draw do
  mount Thredded::Engine => '/forum'


  devise_for :organizations, path: 'organizations', controllers: { sessions: 'organizations/sessions', registrations: 'organizations/registrations' }
  devise_for :users, path: 'users', controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :contacts, only: [:new, :create]
  get 'landing', to: "organizations#landing"
  get 'contact_us', to: "pages#contact_us"

  resources :organizations, only: [:show, :edit, :destroy, :update]

  # resources :users, only: [:new, :create, :show, :edit, :update]
  resources :projects do
    resources :teams, only: [:new, :index, :create]
    get 'classroom', to: :classroom, controller: 'projects'
    resources :proposals, only: [:edit, :show, :create, :destroy, :update]
    get 'proposal/:id/confirm', to: 'proposals#confirm', as: 'proposal_confirm'
  end
  resources :proposals, only: [:index, :destroy, :update]
  resources :teams, only: [:show, :delete, :edit, :update] do
    resources :team_members, only: [:new, :create]
  end

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]

  #for payments
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :description, presence: true
  mount_uploader :photo, PhotoUploader
  def avatar
    if photo.file.nil?
      "http://res.cloudinary.com/jules/image/upload/v1520336238/placeholder.jpg"
    else
      photo
    end
  end
end

app/controllers/organizations/registrations_controller.rb
class Organizations::RegistrationsController < Devise::RegistrationsController
  include Accessible
  private

  def sign_up_params
    params.require(:organization).permit(:name, :description, :location, :website, :photo, :email, :password, :password_confirmation)
  end
end

app/controllers/organizations/sessions_controller.rb
class Organizations::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
  end

  def create
  end

  def update
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def show
    @organization = Organization.find(params[:id])
    authorize @organization
    @projects = Project.where(organization: @organization)
    @markers = [{
        lat: "52.506972",
        lng: "13.391486",
        icon: ActionController::Base.helpers.image_url('pointer.png')
      }]
  end

  def landing
    @organization = Organization.new
    authorize @organization
    @projects = policy_scope(Project)
  end

  def pundit_user
    current_organization
  end
end

app/views/organizations/edit.html.erb
<h2>Edit <%= @organization.name %></h2>

<%= simple_form_for(@organization, html: { method: :put }) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :email, required: true, autofocus: true %>
  <%= f.input :name, required: true, autofocus: true %>
  <%= f.input :description, required: true, autofocus: true %>
  <%= f.input :location, required: true, autofocus: true %>
  <%= f.input :website, required: true, autofocus: true %>
  <%= f.input :photo, required: true, autofocus: true %>

  <%= f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false %>
  <%= f.input :password_confirmation, required: false %>
  <%= f.input :current_password, hint: "we need your current password to confirm your changes", required: true %>
</div>

<div class="form-actions">
  <%= f.button :submit, "Update" %>
</div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= link_to "Cancel my account", organization_path(@organization), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/organizations/landing.html.erb
<div class="header-container" style="background-image: url('<%= cl_image_path 'bg.jpg' %>'); background-size: cover; background-position: center">
  <div class="header-content">
    <div class="text-center intro-text">
      <h1>Look at the projects <br>
      that have been developed through our tool.</h1>
    </div>
  </div>
</div>
<% if organization_signed_in? %>
<div class="one-column-content" style="background-image: url('<%= cl_image_path 'bg3.jpg' %>'); background-size: cover; background-position: center">
  <div class="container-fluid">
    <div class="cta-content">
      <hr>
      <div class="text">
        <h1>Need some help from a developer?</h1>
        <p>Create a new project</p>
      </div>
      <div class="cta-button">
        <%= link_to "Add your project!", new_project_path, class: "custom-primary-btn" %>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="one-column-content" style="background-image: url('<%= cl_image_path 'bg3.jpg' %>'); background-size: cover; background-position: center">
  <div class="container-fluid">
    <div class="cta-content">
      <hr>
      <div class="text">
        <h1>Don't have an Account yet?</h1>
      </div>
      <div class="cta-button">
        <%= link_to "Add your organization and your projects!", new_organization_registration_path, class: "custom-primary-btn" %>
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="container">
  <br>
  <h1 style="color: #005484;" class="text-center">Other projects</h1>
  <br>
  <div class="row">
  <%= render "components/cards" %>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="display">
  <div class="container-fluid" style="background-image: url('<%= cl_image_path @organization.photo %>'); background-size: cover; background-position: center; background-attachment: fixed">
    <div class="cards-container">
      <div class="row no-gutters">
        <div class="col-xs-6">
          <div class="cards-home" style="background-image: url('<%= cl_image_path 'bg3.jpg' %>');">
            <hr>
            <h2><%= @organization.name %></h2>
            <br>
            <p><%= @organization.description %></p>
            <%= link_to "hallo", root_path, class: "custom-primary-btn"  %>
          </div>
        </div>
        <div class="col-xs-6">
          <div class="cards-home" style="background-image: url('<%= cl_image_path 'bg2.jpg' %>');">
            <hr>
            <h2>General information</h2>
            <br>
            <p>
              <%= @organization.location %>
              <br>Website: <%= @organization.website %>
              <br>
              <a href="mailto:#{<%=@organization.email%>}"></a>
              <br>
              <a href="<%= @organization.email %>">Contact</a>
            </p>
          </div>
        </div>
      </div>
    <div class="text-center" style="margin-top: -150px; ">
      <%= link_to "Edit", edit_organization_path, class: "custom-primary-btn" %>
    </div>
    </div>
  </div>
</div>

<div class="container">
  <br>
  <h1 class="text-center">Past projects <%= @organization.name %> worked on</h1>
  <br>
  <div class="row">
    <% @projects.each do |project| %>
    <div class="col-xs-4">
      <%= link_to project_path(project.id) do  %>
      <div class="card">
        <div class="card-category" style="background-image: url('<%= cl_image_path project.photo %>');">
        </div>
        <div class="card-description">
          <h2><%= project.title%></h2>
          <h1><%= project.organization.name %></h1>
          <p class="description-text"><%= project.description %></p>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

<div class="map_height">
  <div
  id="map"
  style="width: 100%;
  height: 100%;"
  data-markers="<%= @markers.to_json %>"
  >
</div>
</div>